steps:

- id: 'Build the container image'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build','.',
    '-f','Dockerfile.prod',
    '-t','gcr.io/$PROJECT_ID/$BUILD_ID',
   ]

- id : 'Push the container image to Container Registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$BUILD_ID']

- id: 'Deploy container image to Cloud Run'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'react-stealcam', '--image', 'gcr.io/$PROJECT_ID/$BUILD_ID', '--region', 'us-central1', '--platform', 'managed']

images:
  - gcr.io/$PROJECT_ID/$BUILD_ID
