version: '3'
services:
  node:
    build: .
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
